CREATE TABLE application (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    workspace_id VARCHAR(255),
    is_public BOOLEAN DEFAULT false,
    pages TEXT,
    published_pages TEXT,
    cloned_from_application_id VARCHAR(255),
    color VARCHAR(255),
    icon VARCHAR(255),
    slug VARCHAR(255),
    evaluation_version INTEGER,
    application_version INTEGER,
    last_edited_at TIMESTAMP WITH TIME ZONE,
    last_deployed_at TIMESTAMP WITH TIME ZONE,
    forking_enabled BOOLEAN,
    is_manual_update BOOLEAN,
    client_schema_version INTEGER,
    server_schema_version INTEGER,
    published_mode_theme_id VARCHAR(255),
    edit_mode_theme_id VARCHAR(255),
    export_with_configuration BOOLEAN,
    fork_with_configuration BOOLEAN,
    is_community_template BOOLEAN,
    forked_from_template_title VARCHAR(255),
    collapse_invisible_widgets BOOLEAN,
    ssh_key TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 